// SINH TỰ ĐỘNG (10/9/2026) — KHÔNG sửa tay trừ khi cố ý.
// Hạt giống chức vụ + THỨ TỰ hiển thị theo từng trang nhân sự, thu hoạch từ
// lưới ProfileCard dựng tay trước đây, để khối "Đội ngũ" tự động giữ nguyên
// curation (Trưởng/Phó bộ môn, Giáo vụ, Thỉnh giảng, thứ tự) khi bỏ lưới tay.
// Khớp người theo `slug` trang cá nhân (chắc nhất); `email` để dự phòng.
// Người CÓ trang nhưng KHÔNG có trong roster sẽ được nối tiếp phía sau với
// chức vụ suy diễn. Về lâu dài nên chuyển vào cột DB cho người tự sửa.

export type RosterEntry = {
  slug: string;
  email: string;
  roleVi: string;
  roleEn: string;
};

export const LISTING_ROSTER: Record<string, RosterEntry[]> = {
  'vat-ly-chat-ran': [
    { slug: 'vat-ly-chat-ran/nhan-su/pgs-ts-tran-quang-trung', email: 'tqtrung@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-chat-ran/nhan-su/ts-le-thuy-thanh-giang', email: 'lttgiang@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-chat-ran/nhan-su/ts-tran-xuan-bao', email: 'txbao@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: '#', email: 'nguyentq@uit.edu.vn', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: 'hvgiang@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-chat-ran/nhan-su/ths-tran-kim-chi', email: 'tkchi@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-chat-ran/nhan-su/ks-nguyen-manh-bao', email: 'nmbao@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-chat-ran/nhan-su/ncs-nguyen-thanh-danh', email: 'ntdanh@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-chat-ran/nhan-su/cn-le-duc-anh', email: 'ldanh@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-chat-ran/nhan-su/ths-nguyen-thi-phuong-thanh', email: 'ntpthanh@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
  ],
  'vat-ly-dia-cau': [
    { slug: 'vat-ly-dia-cau/nhan-su/pgs-ts-nguyen-thanh-van', email: 'ntvan@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-dia-cau/nhan-su/pgs-ts-le-van-anh-cuong', email: 'lvacuong@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-dia-cau/nhan-su/ts-dang-hoai-trung', email: 'dhtrung@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ts-nguyen-nhat-kim-ngan', email: 'nnkngan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ths-vo-nguyen-nhu-lieu', email: 'vnnlieu@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ths-nguyen-van-thuan', email: 'nvthuan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ths-nguyen-ngoc-truong', email: 'nntruong@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/pgs-ts-tran-van-nhac', email: 'tranvannhac@gmail.com', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/pgs-ts-tran-vinh-tuan', email: 'tranvinhtuan@gmail.com', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/pgs-ts-le-quang-toai', email: 'lequangtoai@gmail.com', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/pgs-ts-nguyen-van-giang', email: 'giangnv@igp-vast.vn', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ts-nguyen-ngoc-thu', email: 'thu_geo@yahoo.com', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ts-nguyen-hong-bang', email: 'nguyenhongbang@gmail.com', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dia-cau/nhan-su/ts-luu-viet-hung', email: 'hungluu@hcmute.edu.vn', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
  ],
  'vat-ly-dien-tu': [
    { slug: 'vat-ly-dien-tu/nhan-su/ts-nguyen-chi-nhan', email: 'ncnhan@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-dien-tu/nhan-su/ths-nguyen-phuoc-hoang-khang', email: 'nphkhang@hcmus.edu.vn', roleVi: 'Giáo vụ', roleEn: 'Academic Affairs' },
    { slug: 'vat-ly-dien-tu/nhan-su/pgs-ts-nguyen-van-hieu', email: 'nvhieu@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/ts-ho-thanh-huy', email: 'hothuy@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/ths-nguyen-hoang-quan', email: 'nhquan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/ths-ha-minh-khue', email: 'hmkhue@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/ts-phan-thien-luan', email: 'ptluan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/ths-pham-xuan-hien', email: 'pxhien@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/ths-cao-minh-khoi', email: 'cmkhoi@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/pgs-ts-nguyen-van-hieu-2', email: 'nvhieu@hcmus.edu.vn', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: 'vat-ly-dien-tu/nhan-su/co-tran-thi-kim-lien', email: 'ttklien@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-dien-tu/nhan-su/ths-tran-hoang-nhut', email: 'thnhut@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
    { slug: 'vat-ly-dien-tu/nhan-su/cn-nguyen-ngoc-thao-nhi', email: 'nntnhi@hcmus.edu.vn', roleVi: 'Cán bộ', roleEn: 'Staff' },
  ],
  'vat-ly-ly-thuyet': [
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-vu-quang-tuyen', email: 'vqtuyen@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ths-dang-ngoc-chau', email: 'dnchau@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-truong-ba-ha', email: 'tbha@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ths-nguyen-thi-huyen-nga', email: 'nthnga@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/gs-ts-nguyen-quoc-khanh', email: 'nqkhanh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-nguyen-huu-nha', email: 'nhnha@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-vo-quoc-phong', email: 'vqphong@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: '#', email: 'tnthien@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-tran-nguyen-lan', email: 'tnlan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-huynh-minh-trung', email: 'hmtrung@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ly-thuyet/nhan-su/ts-phan-hong-khiem', email: 'phkhiem@hcmus.edu.vn', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
  ],
  'vat-ly-tin-hoc': [
    { slug: 'vat-ly-tin-hoc/nhan-su/pgsts-huynh-van-tuan', email: 'hvtuan@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-phan-nguyet-thuan', email: 'pnthuan@hcmus.edu.vn', roleVi: 'Phó bộ môn', roleEn: 'Deputy Head' },
    { slug: 'vat-ly-tin-hoc/nhan-su/tsnguyen-chi-linh', email: 'nclinh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-do-duc-cuong', email: 'ddcuong@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/tsnguyen-huynh-tuan-anh', email: 'nhtanh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ts-trinh-thi-ly', email: 'ttly@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/gvcths-hua-thi-hoang-yen', email: 'hthyen@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/cn-nguyen-anh-thu', email: 'nathu@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-ho-van-binh', email: 'hvbinh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/gvcths-huynh-thanh-nhan', email: 'htnhan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-huynh-quoc-viet', email: 'hyqviet@hcmus.edu.vn', roleVi: 'Giáo vụ', roleEn: 'Academic Admin' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-nguyen-vuong-thuy-ngan', email: 'nvtngan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ts-nguyen-quang-khoi', email: 'nqkhoi@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ts-tran-thanh-phong', email: 'trtphong@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ts-truong-trung-kien', email: 'truongkien@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-vo-hoang-thuy-tien', email: 'vhttien@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ncs-nguyen-thi-nhu-quynh', email: 'ntnquynh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ths-nguyen-thi-tu-trinh', email: 'ntttrinh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ts-nguyen-dang-duy', email: 'ndduy@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-tin-hoc/nhan-su/pgsts-le-hoai-bac', email: 'lhbac@hcmus.edu.vn', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
    { slug: 'vat-ly-tin-hoc/nhan-su/ts-nguyen-anh-huy', email: 'nahuy@hcmus.edu.vn', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
    { slug: 'vat-ly-tin-hoc/nhan-su/pgsts-dang-van-liet', email: 'dangvanliet@gmail.com', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
    { slug: 'vat-ly-tin-hoc/nhan-su/pgsts-duong-hoai-nghia', email: 'dhnghia@hcmut.edu.vn', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
    { slug: 'vat-ly-tin-hoc/nhan-su/pgsts-tran-cong-hung', email: 'conghung@pithcm.edu.vn', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
    { slug: 'vat-ly-tin-hoc/nhan-su/gvc-ts-hoang-minh-tri', email: '', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
    { slug: 'vat-ly-tin-hoc/nhan-su/gvths-le-dinh-viet-hai', email: 'ldvhai@vnuhcm.edu.vn', roleVi: 'Thỉnh giảng', roleEn: 'Guest Faculty' },
  ],
  'vat-ly-ung-dung': [
    { slug: 'vat-ly-ung-dung/nhan-su/pgs-ts-le-vu-tuan-hung', email: 'lvthung@hcmus.edu.vn', roleVi: 'Trưởng bộ môn', roleEn: 'Head of Department' },
    { slug: 'vat-ly-ung-dung/nhan-su/pgs-ts-vu-thi-hanh-thu', email: 'vththu@hcmus.edu.vn', roleVi: 'Phó bộ môn', roleEn: 'Deputy Head' },
    { slug: 'vat-ly-ung-dung/nhan-su/ncs-ths-hoang-luong-cuong', email: 'hlcuong@hcmus.edu.vn', roleVi: 'Giáo vụ', roleEn: 'Academic Affairs' },
    { slug: '#', email: 'ntlam@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: '#', email: 'vtnthuy@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/gvc-ts-le-van-ngoc', email: 'lvngoc@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/gvc-ts-le-tran', email: 'ltran@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ts-phan-trung-vinh', email: 'ptvinh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ts-nguyen-huu-ke', email: 'nhke@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ncs-ths-dao-anh-tuan', email: 'daotuan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ts-phan-thi-kieu-loan', email: 'ptkloan@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ncs-ths-nguyen-duy-khanh', email: 'ndkhanh@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ts-ton-nu-quynh-trang', email: 'tnqtrang@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: 'vat-ly-ung-dung/nhan-su/ncs-ths-nguyen-hoang-long', email: 'nhlong@hcmus.edu.vn', roleVi: 'Giảng viên', roleEn: 'Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
    { slug: '#', email: '', roleVi: 'Cán bộ thỉnh giảng', roleEn: 'Visiting Lecturer' },
  ],
};
